// Mock data for development - replace with Supabase queries in production

import { Restaurant, ItemMatchWithItems, MenuItem } from "./types";

export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "Thai Market",
    address: "960 Amsterdam Ave",
    neighborhood: "Upper West Side",
    zip_code: "10025",
    cuisines: ["thai"],
    latitude: 40.7988,
    longitude: -73.9685,
    phone_number: "(212) 280-4575",
    website_url: "https://thaimarketnyc.com",
    direct_ordering_url: "https://thaimarketnyc.com/order",
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/thai-market",
    ubereats_rating: 4.7,
    markup_category: "medium",
    markup_percentage: 18,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-10T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
  },
  {
    id: "2",
    name: "Joe's Pizza",
    address: "520 Columbus Ave",
    neighborhood: "Upper West Side",
    zip_code: "10024",
    cuisines: ["pizza", "italian"],
    latitude: 40.7856,
    longitude: -73.9732,
    phone_number: "(212) 555-1234",
    website_url: "https://joespizzanyc.com",
    direct_ordering_url: null,
    has_direct_delivery: false,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/joes-pizza",
    ubereats_rating: 4.8,
    markup_category: "high",
    markup_percentage: 25,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-09T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-09T12:00:00Z",
  },
  {
    id: "3",
    name: "Sushi Yasaka",
    address: "251 W 72nd St",
    neighborhood: "Upper West Side",
    zip_code: "10023",
    cuisines: ["japanese"],
    latitude: 40.7782,
    longitude: -73.9816,
    phone_number: "(212) 496-8460",
    website_url: "https://sushiyasaka.com",
    direct_ordering_url: "https://sushiyasaka.com/order",
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/sushi-yasaka",
    ubereats_rating: 4.6,
    markup_category: "none",
    markup_percentage: 0,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-11T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-11T12:00:00Z",
  },
  {
    id: "4",
    name: "Curry in a Hurry",
    address: "2400 Broadway",
    neighborhood: "Upper West Side",
    zip_code: "10024",
    cuisines: ["indian"],
    latitude: 40.7905,
    longitude: -73.9742,
    phone_number: "(212) 555-4567",
    website_url: null,
    direct_ordering_url: null,
    has_direct_delivery: false,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/curry-in-a-hurry",
    ubereats_rating: 4.4,
    markup_category: "low",
    markup_percentage: 8,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-08T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-08T12:00:00Z",
  },
  {
    id: "5",
    name: "Taqueria Diana",
    address: "129 W 106th St",
    neighborhood: "Upper West Side",
    zip_code: "10025",
    cuisines: ["mexican"],
    latitude: 40.8007,
    longitude: -73.9632,
    phone_number: "(212) 555-7890",
    website_url: "https://taqueriadiana.com",
    direct_ordering_url: "https://taqueriadiana.com/delivery",
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/taqueria-diana",
    ubereats_rating: 4.5,
    markup_category: "medium",
    markup_percentage: 15,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-10T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
  },
  {
    id: "6",
    name: "Big Nick's Burger Joint",
    address: "2175 Broadway",
    neighborhood: "Upper West Side",
    zip_code: "10024",
    cuisines: ["american"],
    latitude: 40.7838,
    longitude: -73.9787,
    phone_number: "(212) 362-9238",
    website_url: null,
    direct_ordering_url: null,
    has_direct_delivery: false,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/big-nicks",
    ubereats_rating: 4.3,
    markup_category: "high",
    markup_percentage: 22,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-07T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-07T12:00:00Z",
  },
  {
    id: "7",
    name: "Hunan Balcony",
    address: "2596 Broadway",
    neighborhood: "Upper West Side",
    zip_code: "10025",
    cuisines: ["chinese"],
    latitude: 40.7948,
    longitude: -73.9702,
    phone_number: "(212) 865-0400",
    website_url: "https://hunanbalcony.com",
    direct_ordering_url: "https://hunanbalcony.com/order",
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/hunan-balcony",
    ubereats_rating: 4.2,
    markup_category: "low",
    markup_percentage: 5,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-10T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
  },
  {
    id: "8",
    name: "Saigon Grill",
    address: "620 Amsterdam Ave",
    neighborhood: "Upper West Side",
    zip_code: "10024",
    cuisines: ["vietnamese"],
    latitude: 40.7915,
    longitude: -73.9718,
    phone_number: "(212) 875-9072",
    website_url: null,
    direct_ordering_url: null,
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/saigon-grill",
    ubereats_rating: 4.4,
    markup_category: "medium",
    markup_percentage: 12,
    notes: "Call for delivery - they have their own drivers",
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-09T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-09T12:00:00Z",
  },
  {
    id: "9",
    name: "Sal & Carmine Pizza",
    address: "2671 Broadway",
    neighborhood: "Upper West Side",
    zip_code: "10025",
    cuisines: ["pizza"],
    latitude: 40.7968,
    longitude: -73.9695,
    phone_number: "(212) 663-7651",
    website_url: null,
    direct_ordering_url: null,
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/sal-carmines",
    ubereats_rating: 4.7,
    markup_category: "none",
    markup_percentage: 0,
    notes: "Classic NYC slice shop - call for delivery",
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-11T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-11T12:00:00Z",
  },
  {
    id: "10",
    name: "Turkuaz",
    address: "2637 Broadway",
    neighborhood: "Upper West Side",
    zip_code: "10025",
    cuisines: ["mediterranean"],
    latitude: 40.7958,
    longitude: -73.9698,
    phone_number: "(212) 665-9541",
    website_url: "https://turkuazrestaurant.com",
    direct_ordering_url: "https://turkuazrestaurant.com/order",
    has_direct_delivery: true,
    has_pickup: true,
    ubereats_url: "https://www.ubereats.com/store/turkuaz",
    ubereats_rating: 4.5,
    markup_category: "low",
    markup_percentage: 7,
    notes: null,
    actual_menu_url: null,
    actual_prices_verified_at: null,
    last_verified_at: "2026-02-10T12:00:00Z",
    created_at: "2026-02-01T12:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
  },
];

// Mock menu items for price comparison display
const createMockMenuItem = (
  id: string,
  restaurantId: string,
  source: "ubereats" | "actual_menu",
  name: string,
  price: number
): MenuItem => ({
  id,
  restaurant_id: restaurantId,
  source,
  item_name: name,
  item_description: null,
  price,
  category: null,
  scraped_at: "2026-02-10T12:00:00Z",
  created_at: "2026-02-10T12:00:00Z",
  updated_at: "2026-02-10T12:00:00Z",
});

export const mockItemMatches: Record<string, ItemMatchWithItems[]> = {
  "1": [
    // Thai Market
    {
      id: "m1",
      restaurant_id: "1",
      ubereats_item_id: "u1",
      actual_menu_item_id: "a1",
      is_manual_match: false,
      match_confidence: 95,
      price_difference: 300,
      markup_percentage: 18.75,
      created_at: "2026-02-10T12:00:00Z",
      updated_at: "2026-02-10T12:00:00Z",
      ubereats_item: createMockMenuItem("u1", "1", "ubereats", "Pad Thai", 1895),
      actual_menu_item: createMockMenuItem("a1", "1", "actual_menu", "Pad Thai", 1595),
    },
    {
      id: "m2",
      restaurant_id: "1",
      ubereats_item_id: "u2",
      actual_menu_item_id: "a2",
      is_manual_match: false,
      match_confidence: 92,
      price_difference: 350,
      markup_percentage: 19.44,
      created_at: "2026-02-10T12:00:00Z",
      updated_at: "2026-02-10T12:00:00Z",
      ubereats_item: createMockMenuItem("u2", "1", "ubereats", "Green Curry", 2150),
      actual_menu_item: createMockMenuItem("a2", "1", "actual_menu", "Green Curry", 1800),
    },
    {
      id: "m3",
      restaurant_id: "1",
      ubereats_item_id: "u3",
      actual_menu_item_id: "a3",
      is_manual_match: false,
      match_confidence: 88,
      price_difference: 250,
      markup_percentage: 16.67,
      created_at: "2026-02-10T12:00:00Z",
      updated_at: "2026-02-10T12:00:00Z",
      ubereats_item: createMockMenuItem("u3", "1", "ubereats", "Tom Yum Soup", 1750),
      actual_menu_item: createMockMenuItem("a3", "1", "actual_menu", "Tom Yum Soup", 1500),
    },
  ],
  "2": [
    // Joe's Pizza
    {
      id: "m4",
      restaurant_id: "2",
      ubereats_item_id: "u4",
      actual_menu_item_id: "a4",
      is_manual_match: false,
      match_confidence: 98,
      price_difference: 75,
      markup_percentage: 25,
      created_at: "2026-02-09T12:00:00Z",
      updated_at: "2026-02-09T12:00:00Z",
      ubereats_item: createMockMenuItem("u4", "2", "ubereats", "Cheese Slice", 375),
      actual_menu_item: createMockMenuItem("a4", "2", "actual_menu", "Cheese Slice", 300),
    },
    {
      id: "m5",
      restaurant_id: "2",
      ubereats_item_id: "u5",
      actual_menu_item_id: "a5",
      is_manual_match: false,
      match_confidence: 95,
      price_difference: 500,
      markup_percentage: 25,
      created_at: "2026-02-09T12:00:00Z",
      updated_at: "2026-02-09T12:00:00Z",
      ubereats_item: createMockMenuItem("u5", "2", "ubereats", "Large Cheese Pizza", 2500),
      actual_menu_item: createMockMenuItem("a5", "2", "actual_menu", "Large Cheese Pizza", 2000),
    },
  ],
};

// Helper to get restaurants with filters
export function getFilteredRestaurants(filters: {
  cuisine?: string;
  markup_category?: string;
  has_direct_delivery?: boolean;
  search_query?: string;
}): Restaurant[] {
  let results = [...mockRestaurants];

  if (filters.cuisine) {
    results = results.filter((r) => r.cuisines.includes(filters.cuisine as never));
  }

  if (filters.markup_category) {
    results = results.filter((r) => r.markup_category === filters.markup_category);
  }

  if (filters.has_direct_delivery !== undefined) {
    results = results.filter((r) => r.has_direct_delivery === filters.has_direct_delivery);
  }

  if (filters.search_query) {
    const query = filters.search_query.toLowerCase();
    results = results.filter(
      (r) =>
        r.name.toLowerCase().includes(query) ||
        r.cuisines.some((c) => c.toLowerCase().includes(query)) ||
        r.address.toLowerCase().includes(query)
    );
  }

  return results;
}
